<#
.SYNOPSIS
    Decides which files of the installer directory a publish uploads as release assets.

.DESCRIPTION
    A publish globs the installer directory for files carrying the build number and
    uploads what it finds. The directory is also where the run writes what it GENERATES:
    the checksum list, which is a real asset and is named explicitly, and the release
    notes file `RELEASE_NOTES_v<build>.md`, which is not an asset at all - it is passed
    to `gh release create --notes-file` and becomes the body of the release page.

    Nothing goes wrong on a first publish, because the glob runs before the notes are
    written. The residue is what bites: publish the same build number a second time,
    from a working copy where the first run left its notes behind, and the glob now
    carries `RELEASE_NOTES_v<build>.md` into the asset list. The release page then shows
    its own body as a downloadable file.

    So the decision lives here rather than inline in Build.ps1: it is one rule, it has
    one test, and Build.ps1 and that test share the rule itself instead of sharing a
    copy of it.

    The rule refuses generated documents by extension. Markdown in the installer
    directory is always something a run produced, never something a user should
    download: assets are installers, archives and the checksum list.

.NOTES
    Copyright 2026 Julien Bombled
    Licensed under the Apache License, Version 2.0
#>

#Requires -Version 5.1

param()

# Extensions that are never a release asset, whatever their name. Markdown in the
# installer directory is generated by the run itself.
$script:NonAssetExtensions = @('.md')

function Select-PublishArtifact {
    <#
    .SYNOPSIS
        Filters candidate files down to those a publish should upload.
    .PARAMETER Candidate
        The files found in the installer directory for this build number.
    .OUTPUTS
        The subset to upload, in the order given.
    #>
    param(
        [Parameter(Mandatory)] [AllowEmptyCollection()] [System.IO.FileInfo[]] $Candidate
    )

    $kept = @()
    foreach ($file in $Candidate) {
        if ($script:NonAssetExtensions -contains $file.Extension.ToLowerInvariant()) {
            continue
        }

        $kept += $file
    }

    return $kept
}
